apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-10-13T22:55:36Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: webapp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-10-13T22:55:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-10-13T22:56:14Z"
  name: webapp-lb
  namespace: default
  resourceVersion: "10477"
  uid: 49ba9a8d-3948-4cf3-a199-be5bc61ec6fe
spec:
  clusterIP: 10.84.0.238
  clusterIPs:
  - 10.84.0.238
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30165
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.225.133.13
